"""Wire schemas generated from the API's OpenAPI spec.

`models.py` is generated by `just codegen` (datamodel-code-generator, msgspec output) and must not
be edited by hand. The structs model types and JSON parsing only; they carry no validation
constraints, since the API's own output is trusted.
"""
