# generated by datamodel-codegen:
#   filename:  https://api.typesafe.ai/openapi.json

from __future__ import annotations
from typing import Any, TypeAlias
from msgspec import Struct, UNSET, UnsetType


class ChoiceAnswer(Struct, tag_field="type", tag="choice"):
    choice: str
    confidence: float
    probabilities: dict[str, float]


class ChoiceQuestion(Struct, tag_field="type", tag="choice"):
    criteria: dict[str, str | dict[str, Any] | list[Any] | None]
    instructions: str | dict[str, Any] | list[Any] | None | UnsetType = UNSET


class ModelMetadata(Struct):
    name: str
    description: str
    release_date: str


class ModelMetadataList(Struct):
    models: list[ModelMetadata]


class NoulAnswer(Struct, tag_field="type", tag="noul"):
    noul: float


class NoulCriteria(Struct):
    true: str | dict[str, Any] | list[Any] | None | UnsetType = UNSET
    false: str | dict[str, Any] | list[Any] | None | UnsetType = UNSET


class NoulQuestion(Struct, tag_field="type", tag="noul"):
    instructions: str | dict[str, Any] | list[Any] | None | UnsetType = UNSET
    criteria: NoulCriteria | None | UnsetType = UNSET


class ScoreAnswer(Struct, tag_field="type", tag="score"):
    score: float
    confidence: float
    legend: dict[str, str | dict[str, Any] | list[Any]]
    probabilities: dict[str, float]


class ScoreQuestion(Struct, tag_field="type", tag="score"):
    criteria: list[str | dict[str, Any] | list[Any]]
    instructions: str | dict[str, Any] | list[Any] | None | UnsetType = UNSET


class Usage(Struct):
    billing_units: int
    input_tokens: int | None | UnsetType = UNSET
    output_tokens: int | None | UnsetType = UNSET


class ValidationError(Struct):
    loc: list[str | int]
    msg: str
    type: str
    input: Any | UnsetType = UNSET
    ctx: dict[str, Any] | UnsetType = UNSET


Answer: TypeAlias = NoulAnswer | ScoreAnswer | ChoiceAnswer


class HTTPValidationError(Struct):
    detail: list[ValidationError] | UnsetType = UNSET


Question: TypeAlias = NoulQuestion | ChoiceQuestion | ScoreQuestion


class SystemOneRequest(Struct):
    state: str | dict[str, Any] | list[Any]
    model: str
    questions: dict[str, Question]


class SystemOneResponse(Struct):
    model: str
    answers: dict[str, Answer]
    usage: Usage
